// <auto-generated />
namespace Quiron_Medical.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixtTry20151108 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixtTry20151108));
        
        string IMigrationMetadata.Id
        {
            get { return "201511090441411_FixtTry20151108"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
